=== slankka/flinksql-executor/src/main/resources/schema/job.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://slankka.com/schema/bestcoder" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sqljob" type="bes:pfcjobType" xmlns:bes="https://slankka.com/schema/bestcoder"/>
  <xs:complexType name="catalogType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="type"/>
        <xs:attribute type="xs:string" name="defaultDatabase"/>
        <xs:attribute type="xs:string" name="hiveConfDir"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="configurationType">
    <xs:sequence>
      <xs:element type="xs:string" name="pipeline.name"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="configType">
    <xs:sequence>
      <xs:element type="bes:catalogType" name="catalog" xmlns:bes="https://slankka.com/schema/bestcoder"/>
      <xs:element type="bes:configurationType" name="configuration" xmlns:bes="https://slankka.com/schema/bestcoder"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="statementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="id" use="optional"/>
        <xs:attribute type="xs:string" name="ignore" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="statementsType">
    <xs:sequence>
      <xs:element type="bes:statementType" name="statement" maxOccurs="unbounded" minOccurs="0" xmlns:bes="https://slankka.com/schema/bestcoder"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pfcjobType">
    <xs:sequence>
      <xs:element type="bes:configType" name="config" xmlns:bes="https://slankka.com/schema/bestcoder"/>
      <xs:element type="bes:statementsType" name="statements" xmlns:bes="https://slankka.com/schema/bestcoder"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== slankka/flinksql-executor/src/main/resources/job.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqljob xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://slankka.com/schema/bestcoder"
        xsi:schemaLocation="https://slankka.com/schema/bestcoder schema/job.xsd">
    <config>
        <catalog name="pfc" type="hive" defaultDatabase="flink" hiveConfDir="/etc/hive/conf"/>
        <configuration>
            <pipeline.name>
                TEST_SINK_JOB
            </pipeline.name>
        </configuration>
    </config>
    <statements>
        <statement type="DML">
            DROP TABLE IF EXISTS TEST_SINK
        </statement>
        <statement id="TEST_SINK_PRINT"  type="DML">
            <![CDATA[
            CREATE TABLE TEST_SINK (
                id DECIMAL(20, 0)
            ) with (
                'connector' = 'print'
            )
            ]]>
        </statement>
        <statement id="TEST_SINK_ES" type="DML" ignore="true">
            <![CDATA[
            CREATE TABLE TEST_SINK (
                id DECIMAL(20, 0),
                PRIMARY KEY (id) NOT ENFORCED
            ) WITH (
                'connector' = 'elasticsearch-6',
                'hosts' = 'http://127.0.0.1:9200',
                'index' = 'es_billing',
                'document-type' = '_doc',
                'format' = 'json',
                'json.encode.decimal-as-plain-number' = 'true',
                'json.ignore-parse-errors' = 'true',
                'json.fail-on-missing-field' = 'false',
                'json.timestamp-format.standard' = 'ISO-8601'
            )
             ]]>
        </statement>
        <statement type="DML">
            DROP TABLE IF EXISTS test_source_cdc
        </statement>
        <statement id="test_source_cdc" type="DML">
            <![CDATA[
            CREATE TABLE IF NOT EXISTS `test_source_cdc` (
                id DECIMAL(20, 0),
                PRIMARY KEY (id) NOT ENFORCED
            ) WITH (
                'connector' = 'mysql-cdc',
                'hostname' = '127.0.0.1',
                'port' = '3306',
                'database-name' = 'es',
                'server-time-zone' = 'GMT+8',
                'table-name' = 'test_source',
                'username' = 'root',
                'password' = 'root'
            )
            ]]>
        </statement>
        <statement id="createFunction" type="DML">
            create function IF NOT EXISTS FSE AS 'com.slankka.flink.udf.FlinkSQLEnhanced'
        </statement>
        <statement id="jobExecution" type="DML">
            <![CDATA[
            INSERT INTO `TEST_SINK`
                SELECT
                o.id
            FROM
            `es_bill_balance`
            ]]>
        </statement>
    </statements>
</sqljob>
